# Generated by Django 4.2.13 on 2026-05-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_circuit', models.CharField(max_length=150, unique=True, verbose_name='Nom du circuit')),
                ('temp_ambiante_moy', models.FloatField(verbose_name='Température ambiante moyenne (°C)')),
                ('temp_piste_moy', models.FloatField(verbose_name='Température de piste moyenne (°C)')),
                ('nb_virages_lents', models.IntegerField(verbose_name='Nombre de virages lents')),
                ('nb_virages_rapides', models.IntegerField(verbose_name='Nombre de virages rapides')),
                ('degen_moy', models.FloatField(verbose_name='Dégradation moyenne')),
                ('freq_safety_car', models.FloatField(verbose_name='Fréquence historique de Safety Car (%)')),
                ('proba_pluie', models.FloatField(verbose_name='Probabilité de pluie historique (%)')),
                ('cluster_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Label du cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Ecurie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'écurie")),
                ('gamma', models.FloatField(verbose_name="Facteur multiplicateur de l'écurie (γ)")),
                ('T_pit', models.FloatField(verbose_name='Temps moyen aux stands (s)')),
                ('delta', models.FloatField(verbose_name='Exposant de dégradation (δ)')),
                ('profil', models.CharField(max_length=100, verbose_name='Profil stratégique')),
                ('caracteristique', models.TextField(verbose_name='Caractéristique principale')),
            ],
        ),
        migrations.CreateModel(
            name='Pneumatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gomme', models.CharField(choices=[('Soft', 'Soft (S)'), ('Medium', 'Medium (M)'), ('Hard', 'Hard (H)'), ('Inter', 'Intermédiaire (I)'), ('Wet', 'Pluie (W)')], max_length=10, unique=True, verbose_name='Type de gomme')),
                ('alpha', models.FloatField(verbose_name='Taux de dégradation de base (α)')),
                ('duree_max_tours', models.IntegerField(verbose_name='Durée de vie maximale (tours)')),
                ('conditions', models.CharField(max_length=50, verbose_name='Conditions optimales')),
                ('penalite_hors_cond', models.FloatField(verbose_name='Pénalité hors conditions (s/tour)')),
                ('usage', models.CharField(max_length=100, verbose_name='Usage typique')),
            ],
        ),
    ]
